# https://github.com/EPFL-ENAC/epfl-enac-build-push-deploy-action#readme
name: deploy

'on':
  push:
    # branches:
    #   - develop
    tags: ['v*.*.*']

jobs:
  deploy:
    uses: EPFL-ENAC/epfl-enac-build-push-deploy-action/.github/workflows/deploy.yml@v2.2.0
    secrets:
      token: ${{ secrets.CD_TOKEN }}
    with:
      org: epfl-enac
      repo: wanh
      build_context: '["./frontend"]'
